version: '3.7'
services:
  db:
    image: mariadb:latest
    volumes:
      - ./volumes/db:/var/lib/mysql
      - ./config_files/db/tc.cnf:/etc/mysql/conf.d/tc.cnf
      # - ./logs/db:/var/log/mysql
    environment:
      # - MYSQL_ROOT_PASSWORD=${DB_RT_PASSWD}
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      # - MYSQL_PASSWORD=${DB_PASSWD}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    ports:
      - "3306:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
  www:
    image: asia.gcr.io/tekapocart/www:latest
    volumes:
      - ./volumes/html:/var/www/html
      # - ./config_files/php/tc.ini:/usr/local/etc/php/conf.d/tc.ini
      # - ./config_files/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - TC_DOMAIN=${TC_DOMAIN}
      - ADMIN_MAIL=${ADMIN_MAIL}
      - DB_SERVER=db
      - DB_NAME=${DB_NAME}
      # - DB_PASSWD=${DB_PASSWD}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      # - TC_BRANCH=develop
    secrets:
      - db_password
    ports:
      - "9000:9000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - db
    user: "1001"
  nginx:
    image: asia.gcr.io/tekapocart/nginx:latest
    volumes:
      - ./volumes/html:/var/www/html
      # - ./config_files/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      # - ./ca:/etc/ssl
    environment:
      - TC_DOMAIN=${TC_DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - www
secrets:
   db_password:
     file: db_password.txt
   db_root_password:
     file: db_root_password.txt