version: '3.7'
services:
  db:
    image: mariadb:latest
    volumes:
      - ./db:/var/lib/mysql
      - ./dbconf:/etc/mysql/conf.d
      # - ./log/db:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=tekapocart
      - MYSQL_USER=tekapocart
      - MYSQL_PASSWORD=12345678
    ports:
      - "4306:3306"
  www:
    image: asia.gcr.io/tekapocart/www
    volumes:
      - ./html/:/var/www/html/
      - ./phpconf/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      # - ./log/www:/var/log/
    environment:
      - TC_DOMAIN=tekapocart.dev
      - TC_DOMAIN_PORT=4443
      - DB_SERVER=db
      - DB_NAME=tekapocart
      - DB_PASSWD=12345678
      - DB_RT_PASSWD=12345678
      - TC_BRANCH=develop
    depends_on:
      - db
    user: "1001"
  nginx:
    image: nginx:latest
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/timeout.conf:/etc/nginx/conf.d/timeout.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
      - ./ca:/etc/ssl
    ports:
      - "8080:80"
      - "4443:443"
    depends_on:
      - www