version: '3.7'
services:
  db:
    image: mariadb:latest
    volumes:
      - /var/volumes/db:/var/lib/mysql
      - ./config_files/db/tc.cnf:/etc/mysql/conf.d/tc.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_RT_PASSWD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWD}
      - TZ=Asia/Taipei
    ports:
      - "3306:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
  app:
    image: asia.gcr.io/tekapocart/www:latest
    volumes:
      - /var/volumes/html:/var/www/html
      # - ./config_files/php/tc.ini:/usr/local/etc/php/conf.d/tc.ini
      # - ./config_files/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - TC_DOMAIN=${TC_DOMAIN}
      # - TC_DOMAIN_2=${TC_DOMAIN_2}
      # - TC_DOMAIN_3=${TC_DOMAIN_3}
      # - TC_DOMAIN_4=${TC_DOMAIN_4}
      - ADMIN_MAIL=${ADMIN_MAIL}
      - DB_SERVER=db
      - DB_NAME=${DB_NAME}
      - DB_PASSWD=${DB_PASSWD}
      # - TC_BRANCH=develop
    ports:
      - "9000:9000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - db
    user: "1001"
  nginx:
    image: asia.gcr.io/tekapocart/nginx:latest
    # restart: unless-stopped
    volumes:
      - /var/volumes/html:/var/www/html
      # - ./config_files/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/letsencrypt:/etc/letsencrypt
      # - ./ca:/etc/ssl
    environment:
      - TC_DOMAIN=${TC_DOMAIN}
      # - TC_DOMAIN_2=${TC_DOMAIN_2}
      # - TC_DOMAIN_3=${TC_DOMAIN_3}
      # - TC_DOMAIN_4=${TC_DOMAIN_4}
      # - CDN_DOMAIN=${CDN_DOMAIN}
      - ADMIN_MAIL=${ADMIN_MAIL}
      # - TC_VARNISH=1
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - app
  # varnish:
  #   image: asia.gcr.io/tekapocart/varnish:latest
  #   tmpfs:
  #     - /var/lib/varnish:exec
  #   ports:
  #     - "6081:6081"
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "10"
  #   depends_on:
  #     - nginx