version: '3.7'
services:
  db:
    image: mariadb:latest
    volumes:
      - ./volumes/db:/var/lib/mysql
      - ./config_files/db/tc.cnf:/etc/mysql/conf.d/tc.cnf
      # - ./logs/db:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=tekapocart
      - MYSQL_USER=tekapocart
      - MYSQL_PASSWORD=12345678
    ports:
      - "3306:3306"
  www:
    image: asia.gcr.io/tekapocart/www
    volumes:
      - ./volumes/www:/var/www
      - ./config_files/php/tc.ini:/usr/local/etc/php/conf.d/tc.ini
      # - ./logs/www:/var/log/
    environment:
      - TC_DOMAIN=shop.dodoke.net
      - TC_DOMAIN_PORT=4443
      - DB_SERVER=db
      - DB_NAME=tekapocart
      - DB_PASSWD=12345678
      - DB_RT_PASSWD=12345678
      # - TC_BRANCH=develop
    depends_on:
      - db
    user: "1001"
  nginx:
    image: nginx:latest
    volumes:
      - ./volumes/www:/var/www
      - ./config_files/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config_files/nginx/timeout.conf:/etc/nginx/conf.d/timeout.conf
      - ./config_files/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
      - ./ca:/etc/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - www
