version: '3.7'
services:
  db:
    image: mariadb:latest
    volumes:
      - ./volumes/db2:/var/lib/mysql
      - ./config_files/db/tc.cnf:/etc/mysql/conf.d/tc.cnf
      # - ./logs/db:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_RT_PASSWD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWD}
    ports:
      - "3306:3306"
  www:
    image: asia.gcr.io/tekapocart/www:latest
    volumes:
      - ./volumes/www2:/var/www
      # - ./config_files/php/tc.ini:/usr/local/etc/php/conf.d/tc.ini
      # - ./config_files/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      # - ./logs/www:/var/log/
    environment:
      - TC_DOMAIN=${TC_DOMAIN}
      - ADMIN_MAIL=${ADMIN_MAIL}
      - DB_SERVER=db
      - DB_NAME=${DB_NAME}
      - DB_PASSWD=${DB_PASSWD}
      - DB_RT_PASSWD=${DB_RT_PASSWD}
      # - TC_BRANCH=develop
    depends_on:
      - db
    user: "1001"
  nginx:
    image: asia.gcr.io/tekapocart/nginx:latest
    volumes:
      - ./volumes/www2:/var/www
      # - ./config_files/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
      # - ./ca:/etc/ssl
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - TC_DOMAIN=${TC_DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - www
